"""
singularity_engine.py — 奇点主循环（异步）

流程：
  1) await skills.sk_academic_researcher.run_skill() → 架构 + codex 提示
  2) 可选：codex_charger.CodexCharger.run_task() 从回复抽取 Python → 否则使用内置 PyTorch 训练模板
  3) 在 harness/singularity_isolated/run_*/ 下写入 arch.json + train.py 并子进程隔离执行
  4) 读取 metrics.json，按 val_loss / val_win_rate 决定是否晋升到 models/singularity_promoted/

与 Multi-Agent 兼容：使用 asyncio.Lock、状态文件 _singularity_engine_state.json、可注入 notify 回调。
"""

from __future__ import annotations

import asyncio
import concurrent.futures
import json
import logging
import os
import re
import shutil
import sys
import time
import uuid
from pathlib import Path
from typing import Any, Awaitable, Callable, Dict, List, Optional

logger = logging.getLogger(__name__)

BASE = Path(__file__).resolve().parent
SINGULARITY_STATE = BASE / "_singularity_engine_state.json"
HARNESS_ISO = BASE / "harness" / "singularity_isolated"
PROMOTED_DIR = BASE / "models" / "singularity_promoted"

# 晋升阈值（可调）
DEFAULT_MAX_VAL_LOSS = 0.65
DEFAULT_MIN_VAL_WIN_RATE = 0.52

# Blocking filesystem work (large copytree) must not run on the asyncio loop.
_singularity_fs_executor: concurrent.futures.ThreadPoolExecutor | None = None


def _get_singularity_fs_executor() -> concurrent.futures.ThreadPoolExecutor:
    global _singularity_fs_executor
    if _singularity_fs_executor is None:
        _singularity_fs_executor = concurrent.futures.ThreadPoolExecutor(
            max_workers=2,
            thread_name_prefix="singularity_fs",
        )
    return _singularity_fs_executor


def _promote_run_dir_sync(src: Path, dst: Path, promoted_meta: Dict[str, Any]) -> None:
    """rmtree + copytree + promoted.json (runs in ThreadPoolExecutor)."""
    if dst.exists():
        shutil.rmtree(dst)
    shutil.copytree(src, dst)
    (dst / "promoted.json").write_text(
        json.dumps(promoted_meta, indent=2),
        encoding="utf-8",
    )


# ── 内置隔离训练脚本（Codex 失败或未启用时使用）──────────────────────────────

BUNDLED_TRAIN_SCRIPT = r'''#!/usr/bin/env python3
# Generated by singularity_engine (bundled). Reads arch.json, writes metrics.json.
from __future__ import annotations

import json
import math
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent


def mock_ethereum_ohlcv(n: int, seed: int) -> tuple[np.ndarray, np.ndarray]:
    rng = np.random.default_rng(seed)
    ret = rng.normal(0, 0.002, n)
    price = 2000 * np.exp(np.cumsum(ret))
    high = price * (1 + np.abs(rng.normal(0, 0.001, n)))
    low = price * (1 - np.abs(rng.normal(0, 0.001, n)))
    open_ = np.roll(price, 1)
    open_[0] = price[0]
    vol = rng.lognormal(10, 0.4, n)
    ohlcv = np.stack([open_, high, low, price, vol], axis=1).astype(np.float32)
    mu = ohlcv.mean(0, keepdims=True)
    sd = ohlcv.std(0, keepdims=True) + 1e-6
    x = (ohlcv - mu) / sd
    nxt = np.sign(np.diff(price))
    y = np.concatenate([[0.0], nxt.astype(np.float32)])
    y = (y > 0).astype(np.float32)
    return x, y


def build_fragment_mask(T: int, frag: int):
    import torch
    idx = torch.arange(T)
    bi = idx // max(1, frag)
    same = bi.unsqueeze(0) == bi.unsqueeze(1)
    m = torch.zeros(T, T)
    m[~same] = float("-inf")
    return m


def main() -> None:
    arch = json.loads((ROOT / "arch.json").read_text(encoding="utf-8"))
    hp = arch["hyperparams"]
    d_model = int(hp["d_model"])
    n_heads = int(hp["n_heads"])
    frag = int(hp["fragment_len"])
    n_layers = int(hp["transformer_layers"])
    seq_len = int(hp["seq_len"])
    dropout = float(hp.get("dropout", 0.1))

    try:
        import torch
        import torch.nn as nn
    except ImportError:
        print("PyTorch not installed", file=sys.stderr)
        sys.exit(2)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    X, Y = mock_ethereum_ohlcv(4000, seed=42)
    n = X.shape[0]
    split = int(n * 0.8)
    X_train, Y_train = X[:split], Y[:split]
    X_val, Y_val = X[split:], Y[split:]

    def windows(Xa, Ya):
        sx, sy = [], []
        for i in range(len(Xa) - seq_len):
            sx.append(Xa[i : i + seq_len])
            sy.append(Ya[i + seq_len])
        return np.stack(sx), np.array(sy, dtype=np.float32)

    tx, ty = windows(X_train, Y_train)
    vx, vy = windows(X_val, Y_val)

    class FragmentHybrid(nn.Module):
        def __init__(self):
            super().__init__()
            self.proj = nn.Linear(5, d_model)
            self.lstm = nn.LSTM(d_model, d_model, batch_first=True, num_layers=1)
            self.mha = nn.MultiheadAttention(d_model, n_heads, dropout=dropout, batch_first=True)
            enc = nn.TransformerEncoderLayer(
                d_model=d_model, nhead=n_heads, dim_feedforward=d_model * 4,
                dropout=dropout, batch_first=True, activation="gelu",
            )
            self.tr = nn.TransformerEncoder(enc, num_layers=n_layers)
            self.norm = nn.LayerNorm(d_model)
            self.head = nn.Linear(d_model, 1)

        def forward(self, x, frag_mask):
            x = self.proj(x)
            x, _ = self.lstm(x)
            attn_out, _ = self.mha(x, x, x, attn_mask=frag_mask)
            x = self.norm(x + attn_out)
            x = self.tr(x)
            return self.head(x[:, -1, :]).squeeze(-1)

    frag_mask = build_fragment_mask(seq_len, max(1, frag)).to(device)

    model = FragmentHybrid().to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=3e-4)
    loss_fn = nn.BCEWithLogitsLoss()

    def batch(arr_x, arr_y, bs, rng):
        idx = rng.permutation(len(arr_x))[:bs]
        xt = torch.from_numpy(arr_x[idx]).float().to(device)
        yt = torch.from_numpy(arr_y[idx]).float().to(device)
        return xt, yt

    rng = np.random.default_rng(0)
    epochs = 5
    bs = 64
    train_losses = []

    model.train()
    for ep in range(epochs):
        eloss = 0.0
        steps = min(40, max(1, len(tx) // bs))
        for _ in range(steps):
            xb, yb = batch(tx, ty, bs, rng)
            opt.zero_grad()
            logits = model(xb, frag_mask)
            loss = loss_fn(logits, yb)
            loss.backward()
            opt.step()
            eloss += float(loss.item())
        train_losses.append(eloss / steps)

    model.eval()
    with torch.no_grad():
        vt = torch.from_numpy(vx).float().to(device)
        vty = torch.from_numpy(vy).float().to(device)
        logits = model(vt, frag_mask)
        vloss = float(loss_fn(logits, vty).item())
        pred = (torch.sigmoid(logits) > 0.5).float()
        acc = float((pred == vty).float().mean().item())

    metrics = {
        "train_loss": float(train_losses[-1]) if train_losses else 0.0,
        "val_loss": vloss,
        "val_win_rate": acc,
        "epochs": epochs,
        "architecture_id": arch.get("architecture_id", "unknown"),
        "device": str(device),
        "bundled": True,
    }
    (ROOT / "metrics.json").write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    torch.save(
        {
            "state_dict": model.state_dict(),
            "hp": hp,
            "seq_len": seq_len,
            "fragment_len": frag,
            "metrics": metrics,
        },
        ROOT / "model.pt",
    )
    print(json.dumps(metrics))


if __name__ == "__main__":
    main()
'''


def _load_state() -> Dict[str, Any]:
    if SINGULARITY_STATE.exists():
        try:
            return json.loads(SINGULARITY_STATE.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass
    return {"runs": [], "promoted": []}


def _save_state(data: Dict[str, Any]) -> None:
    try:
        tmp = str(SINGULARITY_STATE) + ".tmp"
        Path(tmp).write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
        os.replace(tmp, SINGULARITY_STATE)
    except OSError as e:
        logger.warning("singularity state save failed: %s", e)


def hook_after_paper_payload(payload: Dict[str, Any]) -> None:
    """兼容 sk_paper_to_alpha：将论文载荷排入奇点队列。"""
    st = _load_state()
    q = st.get("paper_queue", [])
    q.append({"ts": time.time(), "payload": payload})
    st["paper_queue"] = q[-200:]
    _save_state(st)


def extract_python_from_codex_output(text: str) -> Optional[str]:
    """从 Codex / LLM 回复中提取 ```python ... ``` 代码块。"""
    if not text:
        return None
    m = re.search(r"```python\s*([\s\S]*?)```", text, re.IGNORECASE)
    if m:
        return m.group(1).strip()
    m2 = re.search(r"```\s*([\s\S]*?)```", text)
    if m2 and "import " in m2.group(1):
        return m2.group(1).strip()
    return None


class SingularityEngine:
    """
    主循环引擎。可在后台 task 中 await engine.run_cycle()。
    """

    def __init__(
        self,
        *,
        use_codex: Optional[bool] = None,
        max_val_loss: float = DEFAULT_MAX_VAL_LOSS,
        min_val_win_rate: float = DEFAULT_MIN_VAL_WIN_RATE,
        codex_timeout: int = 180,
        on_event: Optional[Callable[[str, Dict[str, Any]], Awaitable[None]]] = None,
    ) -> None:
        if use_codex is None:
            use_codex = os.environ.get("SINGULARITY_USE_CODEX", "").lower() in ("1", "true", "yes")
        self.use_codex = use_codex
        self.max_val_loss = max_val_loss
        self.min_val_win_rate = min_val_win_rate
        self.codex_timeout = codex_timeout
        self.on_event = on_event
        self._lock = asyncio.Lock()

    async def _emit(self, event: str, payload: Dict[str, Any]) -> None:
        if self.on_event:
            try:
                await self.on_event(event, payload)
            except Exception as e:
                logger.debug("on_event failed: %s", e)

    async def run_cycle(self) -> Dict[str, Any]:
        """单次完整闭环：学术 → 代码 → harness 训练 → 晋升判定。"""
        async with self._lock:
            return await self._run_cycle_unlocked()

    async def _run_cycle_unlocked(self) -> Dict[str, Any]:
        from skills.sk_academic_researcher import run_skill as academic_run

        t0 = time.time()
        await self._emit("cycle_start", {})

        research = await academic_run({"max_results": 5})
        if not research.get("ok"):
            err = {"ok": False, "stage": "research", "error": research.get("error", "unknown")}
            await self._emit("cycle_error", err)
            return err

        architecture = research["architecture"]
        codex_prompt = research["codex_prompt"]
        script_body: Optional[str] = None
        codegen_source = "bundled"

        if self.use_codex:
            try:
                from codex_charger import CodexCharger

                charger = CodexCharger()
                result = await charger.run_task(codex_prompt, timeout_seconds=self.codex_timeout)
                if result.get("success"):
                    script_body = extract_python_from_codex_output(result.get("output") or "")
                    if script_body:
                        codegen_source = "codex_charger"
                else:
                    logger.warning("Codex task failed: %s", result.get("error"))
            except Exception as e:
                logger.warning("CodexCharger unavailable: %s", e)

        if not script_body:
            script_body = BUNDLED_TRAIN_SCRIPT
            codegen_source = "bundled"

        run_id = f"{int(time.time())}_{uuid.uuid4().hex[:8]}"
        run_dir = HARNESS_ISO / f"run_{run_id}"
        run_dir.mkdir(parents=True, exist_ok=True)
        (run_dir / "arch.json").write_text(json.dumps(architecture, indent=2, ensure_ascii=False), encoding="utf-8")
        (run_dir / "train.py").write_text(script_body, encoding="utf-8")

        proc = await asyncio.create_subprocess_exec(
            sys.executable,
            str(run_dir / "train.py"),
            cwd=str(run_dir),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env={**os.environ, "PYTHONUTF8": "1"},
        )
        out_b, err_b = await proc.communicate()
        stdout = (out_b or b"").decode("utf-8", errors="replace")
        stderr = (err_b or b"").decode("utf-8", errors="replace")

        metrics_path = run_dir / "metrics.json"
        metrics: Dict[str, Any] = {}
        if metrics_path.exists():
            try:
                metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
            except json.JSONDecodeError:
                metrics = {"parse_error": True, "raw_stdout": stdout[-2000:]}
        else:
            metrics = {
                "missing_metrics": True,
                "returncode": proc.returncode,
                "stderr_tail": stderr[-1500:],
                "stdout_tail": stdout[-1500:],
            }

        promoted = False
        reason = "criteria_not_met"
        if proc.returncode == 0 and not metrics.get("missing_metrics"):
            vl = float(metrics.get("val_loss", 99))
            vw = float(metrics.get("val_win_rate", 0))
            if vl <= self.max_val_loss and vw >= self.min_val_win_rate:
                promoted = True
                reason = "loss_and_winrate_ok"
                PROMOTED_DIR.mkdir(parents=True, exist_ok=True)
                dst = PROMOTED_DIR / f"model_{run_id}"
                if dst.exists():
                    shutil.rmtree(dst)
                shutil.copytree(run_dir, dst)
                (dst / "promoted.json").write_text(
                    json.dumps({"promoted_at": time.time(), "metrics": metrics}, indent=2),
                    encoding="utf-8",
                )
            else:
                reason = f"val_loss={vl:.4f} (need <= {self.max_val_loss}) or win_rate={vw:.4f} (need >= {self.min_val_win_rate})"
        else:
            reason = f"subprocess_exit_{proc.returncode}"

        record = {
            "run_id": run_id,
            "ts": time.time(),
            "duration_sec": time.time() - t0,
            "research_source": research.get("source"),
            "architecture_id": architecture.get("architecture_id"),
            "codegen_source": codegen_source,
            "metrics": metrics,
            "promoted": promoted,
            "promotion_reason": reason,
            "run_dir": str(run_dir),
        }

        st = _load_state()
        runs = st.get("runs", [])
        runs.append(record)
        st["runs"] = runs[-100:]
        if promoted:
            prom = st.get("promoted", [])
            prom.append({"run_id": run_id, "path": str(PROMOTED_DIR / f"model_{run_id}"), "metrics": metrics})
            st["promoted"] = prom[-50:]
        _save_state(st)

        await self._emit("cycle_complete", record)
        return {"ok": True, **record}


async def run_daemon(interval_sec: float = 3600.0, **engine_kw: Any) -> None:
    """可选后台循环：多 Agent 可 create_task(run_daemon(...))。"""
    eng = SingularityEngine(**engine_kw)
    while True:
        try:
            await eng.run_cycle()
        except asyncio.CancelledError:
            raise
        except Exception as e:
            logger.exception("singularity daemon cycle error: %s", e)
        await asyncio.sleep(interval_sec)


def run_sandbox_training_episodes(n: int = 3) -> List[Dict[str, Any]]:
    """兼容旧 API：同步跑 n 次子进程训练（单事件循环，避免嵌套 asyncio.run）。"""

    async def _sequential() -> List[Dict[str, Any]]:
        eng = SingularityEngine(use_codex=False)
        out: List[Dict[str, Any]] = []
        for _ in range(max(1, n)):
            out.append(await eng.run_cycle())
        return out

    return asyncio.run(_sequential())


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s")
    r = asyncio.run(SingularityEngine(use_codex=False).run_cycle())
    print(json.dumps({k: r[k] for k in r if k in ("ok", "promoted", "promotion_reason", "metrics", "codegen_source")}, indent=2))
