#!/usr/bin/env python3
# Generated by singularity_engine (bundled). Reads arch.json, writes metrics.json.
from __future__ import annotations

import json
import math
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent


def mock_ethereum_ohlcv(n: int, seed: int) -> tuple[np.ndarray, np.ndarray]:
    rng = np.random.default_rng(seed)
    ret = rng.normal(0, 0.002, n)
    price = 2000 * np.exp(np.cumsum(ret))
    high = price * (1 + np.abs(rng.normal(0, 0.001, n)))
    low = price * (1 - np.abs(rng.normal(0, 0.001, n)))
    open_ = np.roll(price, 1)
    open_[0] = price[0]
    vol = rng.lognormal(10, 0.4, n)
    ohlcv = np.stack([open_, high, low, price, vol], axis=1).astype(np.float32)
    mu = ohlcv.mean(0, keepdims=True)
    sd = ohlcv.std(0, keepdims=True) + 1e-6
    x = (ohlcv - mu) / sd
    nxt = np.sign(np.diff(price))
    y = np.concatenate([[0.0], nxt.astype(np.float32)])
    y = (y > 0).astype(np.float32)
    return x, y


def build_fragment_mask(T: int, frag: int):
    import torch
    idx = torch.arange(T)
    bi = idx // max(1, frag)
    same = bi.unsqueeze(0) == bi.unsqueeze(1)
    m = torch.zeros(T, T)
    m[~same] = float("-inf")
    return m


def main() -> None:
    arch = json.loads((ROOT / "arch.json").read_text(encoding="utf-8"))
    hp = arch["hyperparams"]
    d_model = int(hp["d_model"])
    n_heads = int(hp["n_heads"])
    frag = int(hp["fragment_len"])
    n_layers = int(hp["transformer_layers"])
    seq_len = int(hp["seq_len"])
    dropout = float(hp.get("dropout", 0.1))

    try:
        import torch
        import torch.nn as nn
    except ImportError:
        print("PyTorch not installed", file=sys.stderr)
        sys.exit(2)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    X, Y = mock_ethereum_ohlcv(4000, seed=42)
    n = X.shape[0]
    split = int(n * 0.8)
    X_train, Y_train = X[:split], Y[:split]
    X_val, Y_val = X[split:], Y[split:]

    def windows(Xa, Ya):
        sx, sy = [], []
        for i in range(len(Xa) - seq_len):
            sx.append(Xa[i : i + seq_len])
            sy.append(Ya[i + seq_len])
        return np.stack(sx), np.array(sy, dtype=np.float32)

    tx, ty = windows(X_train, Y_train)
    vx, vy = windows(X_val, Y_val)

    class FragmentHybrid(nn.Module):
        def __init__(self):
            super().__init__()
            self.proj = nn.Linear(5, d_model)
            self.lstm = nn.LSTM(d_model, d_model, batch_first=True, num_layers=1)
            self.mha = nn.MultiheadAttention(d_model, n_heads, dropout=dropout, batch_first=True)
            enc = nn.TransformerEncoderLayer(
                d_model=d_model, nhead=n_heads, dim_feedforward=d_model * 4,
                dropout=dropout, batch_first=True, activation="gelu",
            )
            self.tr = nn.TransformerEncoder(enc, num_layers=n_layers)
            self.norm = nn.LayerNorm(d_model)
            self.head = nn.Linear(d_model, 1)

        def forward(self, x, frag_mask):
            x = self.proj(x)
            x, _ = self.lstm(x)
            attn_out, _ = self.mha(x, x, x, attn_mask=frag_mask)
            x = self.norm(x + attn_out)
            x = self.tr(x)
            return self.head(x[:, -1, :]).squeeze(-1)

    frag_mask = build_fragment_mask(seq_len, max(1, frag)).to(device)

    model = FragmentHybrid().to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=3e-4)
    loss_fn = nn.BCEWithLogitsLoss()

    def batch(arr_x, arr_y, bs, rng):
        idx = rng.permutation(len(arr_x))[:bs]
        xt = torch.from_numpy(arr_x[idx]).float().to(device)
        yt = torch.from_numpy(arr_y[idx]).float().to(device)
        return xt, yt

    rng = np.random.default_rng(0)
    epochs = 5
    bs = 64
    train_losses = []

    model.train()
    for ep in range(epochs):
        eloss = 0.0
        steps = min(40, max(1, len(tx) // bs))
        for _ in range(steps):
            xb, yb = batch(tx, ty, bs, rng)
            opt.zero_grad()
            logits = model(xb, frag_mask)
            loss = loss_fn(logits, yb)
            loss.backward()
            opt.step()
            eloss += float(loss.item())
        train_losses.append(eloss / steps)

    model.eval()
    with torch.no_grad():
        vt = torch.from_numpy(vx).float().to(device)
        vty = torch.from_numpy(vy).float().to(device)
        logits = model(vt, frag_mask)
        vloss = float(loss_fn(logits, vty).item())
        pred = (torch.sigmoid(logits) > 0.5).float()
        acc = float((pred == vty).float().mean().item())

    metrics = {
        "train_loss": float(train_losses[-1]) if train_losses else 0.0,
        "val_loss": vloss,
        "val_win_rate": acc,
        "epochs": epochs,
        "architecture_id": arch.get("architecture_id", "unknown"),
        "device": str(device),
        "bundled": True,
    }
    (ROOT / "metrics.json").write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    print(json.dumps(metrics))


if __name__ == "__main__":
    main()
